---
title: Voorkom dat een sprite ondersteboven gaat
hero_image: images/banner.png
description: Voorkom dat een sprite ondersteboven gaat
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Voorkom dat een sprite ondersteboven gaat

