---
title: Impedir que um sprite fique de cabeça para baixo
hero_image: images/banner.png
description: Impedir que um sprite fique de cabeça para baixo
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Impedir que um sprite fique de cabeça para baixo

