---
title: Evita que un objeto se ponga boca abajo
hero_image: images/banner.png
description: Evita que un objeto se ponga boca abajo
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - 
    title: Evita que un objeto se ponga boca abajo

