---
title: Stop a sprite going upside down
hero_image: images/banner.png
description: Stop a sprite going upside down
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - 
    title: Stop a sprite going upside down

