---
title: Arrêter un sprite allant à l'envers
hero_image: images/banner.png
description: Arrêter un sprite allant à l'envers
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - 
    title: Arrêter un sprite allant à l'envers

